### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by JoshMacSween** [yegrb/yegrb.com#16]
Tests need to be improved. ```rails t ``` runs errors. 
Any approaches to fixing it?

**Comment by alanvardy** [comment]
I'm pretty sure that this issues is the fixtures. You can read up on fixtures under the tests section of rails guides.

If you find and delete the fixtures files (you don't need to delete the folder) the tests should pass.

Try and fix!

**Comment by alanvardy** [comment]
The issue was a bit more in depth than I expected... I changed some routes, fixtures, and a few tests to get things back to baseline. I did this in PR #17
