### ISSUE TITLE
Planning and wireframe

### ISSUE THREAD

**Issue by alanvardy** [yegrb/yegrb.com#2]
Lets have a discussion on what this site should have and what it should look like... And generate some new issues off of that.

**Comment by Claudwin** [comment]
Would you want to add the meetup api widget to the website ?

**Comment by alanvardy** [comment]
Yes. Not an immediate priority but I would like to pull in information from the Meetup.com API about upcoming meetups.

https://www.meetup.com/meetup_api/

Which widget are you referring to? I found the widget foundry one but it would show a generic startup edmonton widget.

**Comment by MarkBennett** [comment]
> Yes. Not an immediate priority but I would like to pull in information from the Meetup.com API about upcoming meetups.

Looks like there's a Meetup.com API gem. Can't vouch for it's quality but might be a place to start.

**Comment by alanvardy** [comment]
Thanks! The gem is at https://github.com/cranieri/meetup_client and we should give it a shot before going with rest_client.

**Comment by MarkBennett** [comment]
> Thanks! The gem is at https://github.com/cranieri/meetup_client and we should give it a shot before going with rest_client.

Lol. Totally forgot to include the link. 🙄

**Comment by alanvardy** [comment]
I've made a separate issue for the API. What else?

**Comment by MarkBennett** [comment]
Speaking from my experience, most people visiting the page want to know the when, where, what for the next meetup. Others want to access an archive of the talks and notes from the past events. Beyond that people like general information like information about getting to the meetup, what to bring, how to find the meetup on social media, how to connect with members (Slack/mailing list). Sometimes a list of resources for learners is nice too. You may also need a sponsor logo or two depending on what you work out there. Oh, I'd also include a link to the Code of Conduct that you follow.

That's my quick brain dump. Hope it helps! ;)

**Comment by alanvardy** [comment]
:+1: Awesome! 

1. When, where, what for the next meetup
2. Archive of the talks and notes from the past events. 
3. General information like information about getting to the meetup, 
4. What to bring to the meetup
5. How to find the meetup on social media
6. How to connect with members (Slack/mailing list)
7. List of resources for learners is nice too
8. Sponsor logo or two depending on what you work out there. 
9. Link to the Code of Conduct that you follow.

**Comment by alanvardy** [comment]
All mentioned ideas have been extracted out into separate issues. Closed with thanks!
