### ISSUE TITLE
Make sure all pages have titles

### ISSUE THREAD

**Issue by alanvardy** [yegrb/yegrb.com#68]
Up at the top of the view template

**Comment by alanvardy** [comment]
Some pages have titles (in the title bar) and some don't. Take a look at how I have implemented them and make sure that all pages have titles.

After that is done, you can convert them over to 'yield' like I did on my alanvardy and corneliakelinske sites if you want. Or just leave them as is!

**Comment by alanvardy** [comment]
I am assigning an instance variable in the view on this site, but my other sites mentioned use yield.

**Comment by JoshMacSween** [comment]
I think its safe to say this issue is closed?

**Comment by alanvardy** [comment]
I think that we are missing page titles in the pages that are only accessible by admins/editors.
